version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=db
    volumes:
      - mongo-data:/data/db
    networks:
      - dating-app-network # Đặt tên mạng chung

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - dating-app-network # Đặt tên mạng chung

  dating-app-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5176:5176" # Ánh xạ cổng 5176 của máy chủ sang cổng 8080 của container
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__MongoDB: "mongodb://admin:pass@mongodb:27017/db?authSource=admin"
    depends_on:
      - mongodb
    networks:
      - dating-app-network # Đặt tên mạng chung

# Define named volumes
volumes:
  mongo-data:
    driver: local
networks:
  dating-app-network:
    driver: bridge
    external: true
